# Netlify configuration for BubblePop game
[build]
  command = "npm run build"
  publish = "dist"
  
  # Environment variables for build
  [build.environment]
    NODE_VERSION = "18"
    NPM_VERSION = "9"

# Production context
[context.production]
  command = "npm run build"
  
  [context.production.environment]
    NODE_ENV = "production"
    VITE_ANALYTICS_ENABLED = "true"

# Deploy preview context
[context.deploy-preview]
  command = "npm run build:staging"
  
  [context.deploy-preview.environment]
    NODE_ENV = "staging"
    VITE_ANALYTICS_ENABLED = "false"

# Branch deploy context
[context.branch-deploy]
  command = "npm run build:dev"
  
  [context.branch-deploy.environment]
    NODE_ENV = "development"
    VITE_ANALYTICS_ENABLED = "false"

# Redirects for SPA routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Headers for optimal caching and security
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
    X-Content-Type-Options = "nosniff"

[[headers]]
  for = "/*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
    X-Content-Type-Options = "nosniff"

[[headers]]
  for = "/*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
    X-Content-Type-Options = "nosniff"

[[headers]]
  for = "/index.html"
  [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Permissions-Policy = "camera=(), microphone=(), geolocation=()"

[[headers]]
  for = "/*.html"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

# Edge functions (if needed for future features)
# [[edge_functions]]
#   function = "game-analytics"
#   path = "/api/analytics/*"